# Generated by Django 5.2 on 2025-06-03 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('numero_serie', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_dispositivo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id_invitado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('apellido_materno', models.CharField(max_length=50)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('motivo_visita', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invitados',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
                ('programa_educativo_area', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100)),
                ('contrasenia', models.CharField(max_length=100)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('modalidad', models.CharField(max_length=50)),
                ('materia', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('grupo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('sala', models.TextField(max_length=1)),
                ('id_horario', models.ForeignKey(db_column='id_horario_id', on_delete=django.db.models.deletion.CASCADE, to='auth_app.horario')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario_id', on_delete=django.db.models.deletion.CASCADE, to='auth_app.usuario')),
            ],
            options={
                'db_table': 'reservaciones',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Vigente', 'Vigente'), ('Devuelto', 'Devuelto'), ('Atrasado', 'Atrasado')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('firma', models.CharField(max_length=45)),
                ('proposito', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='auth_app.dispositivo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario_id', on_delete=django.db.models.deletion.CASCADE, to='auth_app.usuario')),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
        migrations.CreateModel(
            name='HuellaDactilar',
            fields=[
                ('id_huella', models.AutoField(primary_key=True, serialize=False)),
                ('huella', models.TextField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='huellas', to='auth_app.usuario')),
            ],
            options={
                'db_table': 'huellas_dactilares',
            },
        ),
        migrations.CreateModel(
            name='AccesoDiario',
            fields=[
                ('id_acceso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('uso_maquina', models.CharField(max_length=2)),
                ('sala', models.TextField(max_length=1)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario_id', on_delete=django.db.models.deletion.CASCADE, to='auth_app.usuario')),
            ],
            options={
                'db_table': 'accesos_diarios',
            },
        ),
    ]
